### ISSUE TITLE
KeyError: 'title'

### ISSUE THREAD

**Issue by blackami** [sharkone/BitTorrent.bundle#70]
Thanks sharkone for fixing the previous issue, i commented there but I am not sure if you will see that since you closed it.

I guess with the new changes there are many cases where titles are not unique anymore and seems like that causes plex to fail... This is just my guess, i know very little about plex or your code, but i just see error saying "KeyError: 'title'"

**Comment by sharkone** [comment]
Could you provide repro steps?

**Comment by blackami** [comment]
I tried to watch /channel/%2Fvideo%2Fbittorrent%2Ftvshows%2Fseason%3Fseason_index%3D2%26title%3DSeason%2B2%26trakt_slug%3Dthe-last-man-on-earth%26show_title%3DThe%2BLast%2BMan%2Bon%2BEarth/%2Fvideo%2Fbittorrent%2Ftvshows%2Fepisode%3Fseason_index%3D2%26trakt_slug%3Dthe-last-man-on-earth%26episode_index%3D15%26show_title%3DThe%2BLast%2BMan%2Bon%2BEarth
and it failed very quickly.

I checked the error log, it says

2016-04-18 22:52:34,378 (1158) :  DEBUG (networking:161) - Fetching 'http://scrapyard.en-mousse.org/api/show/the-last-man-on-earth/season/2/episode/15' from the HTTP cache
2016-04-18 22:52:34,390 (1158) :  INFO (logkit:16) - http://scrapyard.en-mousse.org/api/show/the-last-man-on-earth/season/2/episode/15
2016-04-18 22:52:34,391 (1158) :  CRITICAL (core:574) - Exception (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ee6e505\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\runtime.py", line 843, in handle_request
    result = f(**d)
  File "C:\Users\......\AppData\Local\Plex Media Server\Plug-ins\BitTorrent.bundle\Contents\Code\tvshows_menu.py", line 167, in episode_menu
    episode_object.title   = json_item['title']
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-ee6e505\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 108, in <lambda>
    _getitem_           = lambda x, y: x.__getitem__(y),
KeyError: 'title'


I checked the json and found that there are two identical titles:
"The Last Man On Earth S02E14 HDTV x264-KILLERS"

{
      "title": "The Last Man On Earth S02E14 HDTV x264-KILLERS",
      "source": "KickassTorrents",
      "size": 147431753,
      "seeds": 267,
      "peers": 31,
      "link": "magnet:?dn=The+Last+Man+On+Earth+S02E14+HDTV+x264-KILLERS&xt=urn:btih:991D40D95900356B88CD8F6FDD9120B7FD313EF2&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80"
    }, 

    {
      "title": "The Last Man On Earth S02E14 HDTV x264-KILLERS",
      "source": "KickassTorrents",
      "size": 159399196,
      "seeds": 3,
      "peers": 10,
      "link": "magnet:?dn=The+Last+Man+On+Earth+S02E14+HDTV+x264-KILLERS&xt=urn:btih:7F421149DF0C943F95A0259BE16F5894559DE332&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80"
    },

Hope that helps...

**Comment by sharkone** [comment]
Should be fixed with sharkone/scrapyard.js@255ba79d5ebd3af03c372f14177b47230194b62e

This particular release on EZTV had no title.

**Comment by blackami** [comment]
hmm.. no, same thing so far...

**Comment by sharkone** [comment]
Try restarting your server. It caches pages for about an hour I think. If it still fails, just wait some time. 
http://scrapyard.en-mousse.org/api/show/the-last-man-on-earth/season/2/episode/15 no longer returns magnets with no titles.

**Comment by blackami** [comment]
I did restart and i will try again. But i still have the old json open, there are no entries without titles.. Does it work in your plex? I will try tomorrow again and will let you know, thanks for the quick responses.

**Comment by sharkone** [comment]
Yup everything works fine for me.
Let me know if you still have issues tomorrow.

**Comment by blackami** [comment]
I cleared cache and it does work! Excellent! Thanks a lot!

**Comment by blackami** [comment]
If you dont mind i will edit my message to remove the torrent info :)
